[2023-08-03T21:52:20.336+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiago_dag.my_task manual__2023-08-03T21:19:39.475221+00:00 [queued]>
[2023-08-03T21:52:20.367+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiago_dag.my_task manual__2023-08-03T21:19:39.475221+00:00 [queued]>
[2023-08-03T21:52:20.367+0000] {taskinstance.py:1308} INFO - Starting attempt 12 of 14
[2023-08-03T21:52:20.416+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): my_task> on 2023-08-03 21:19:39.475221+00:00
[2023-08-03T21:52:20.428+0000] {standard_task_runner.py:57} INFO - Started process 99 to run task
[2023-08-03T21:52:20.436+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tiago_dag', 'my_task', 'manual__2023-08-03T21:19:39.475221+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmpx_rmuscg']
[2023-08-03T21:52:20.445+0000] {standard_task_runner.py:85} INFO - Job 135: Subtask my_task
[2023-08-03T21:52:20.563+0000] {task_command.py:410} INFO - Running <TaskInstance: tiago_dag.my_task manual__2023-08-03T21:19:39.475221+00:00 [running]> on host 8e6c163cc56a
[2023-08-03T21:52:20.775+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiago_dag' AIRFLOW_CTX_TASK_ID='my_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-03T21:19:39.475221+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-03T21:19:39.475221+00:00'
[2023-08-03T21:52:20.779+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-03T21:52:20.781+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'Tiago' > /opt/***/utils/text.txt "]
[2023-08-03T21:52:20.800+0000] {subprocess.py:86} INFO - Output:
[2023-08-03T21:52:20.807+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/utils/text.txt: Permission denied
[2023-08-03T21:52:20.808+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-03T21:52:20.829+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-03T21:52:20.836+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=tiago_dag, task_id=my_task, execution_date=20230803T211939, start_date=20230803T215220, end_date=20230803T215220
[2023-08-03T21:52:20.860+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 135 for task my_task (Bash command failed. The command returned a non-zero exit code 1.; 99)
[2023-08-03T21:52:20.889+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-03T21:52:20.920+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
