[2023-08-03T21:57:24.471+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiago_dag.my_task manual__2023-08-03T21:19:39.475221+00:00 [queued]>
[2023-08-03T21:57:24.486+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiago_dag.my_task manual__2023-08-03T21:19:39.475221+00:00 [queued]>
[2023-08-03T21:57:24.486+0000] {taskinstance.py:1308} INFO - Starting attempt 13 of 14
[2023-08-03T21:57:24.508+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): my_task> on 2023-08-03 21:19:39.475221+00:00
[2023-08-03T21:57:24.515+0000] {standard_task_runner.py:57} INFO - Started process 84 to run task
[2023-08-03T21:57:24.520+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tiago_dag', 'my_task', 'manual__2023-08-03T21:19:39.475221+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmp16nky_j1']
[2023-08-03T21:57:24.524+0000] {standard_task_runner.py:85} INFO - Job 167: Subtask my_task
[2023-08-03T21:57:24.589+0000] {task_command.py:410} INFO - Running <TaskInstance: tiago_dag.my_task manual__2023-08-03T21:19:39.475221+00:00 [running]> on host a0decf253b1b
[2023-08-03T21:57:24.715+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiago_dag' AIRFLOW_CTX_TASK_ID='my_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-03T21:19:39.475221+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-03T21:19:39.475221+00:00'
[2023-08-03T21:57:24.723+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-03T21:57:24.724+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'Tiago' > /opt/***/utils/text.txt "]
[2023-08-03T21:57:24.739+0000] {subprocess.py:86} INFO - Output:
[2023-08-03T21:57:24.752+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/utils/text.txt: Permission denied
[2023-08-03T21:57:24.753+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-03T21:57:24.766+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-03T21:57:24.773+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=tiago_dag, task_id=my_task, execution_date=20230803T211939, start_date=20230803T215724, end_date=20230803T215724
[2023-08-03T21:57:24.795+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 167 for task my_task (Bash command failed. The command returned a non-zero exit code 1.; 84)
[2023-08-03T21:57:24.812+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-03T21:57:24.834+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
